#!/usr/bin/env python

# This script print in stdout a JSON data of the result of the web scraping

import os, sys, json
import typing

def print_module_error(module_name):
    print(f"{module_name} is required! Maybe you forget to enable a virtual environment!")

try:
    import bs4
except ModuleNotFoundError:
    print_module_error("bs4")
    sys.exit(2)


try:
    from rich.console import Console
except ModuleNotFoundError:
    print_module_error("rich")
    sys.exit(3)


def get_class(tag, class_name) -> bs4.Tag :
    """
    Search for a tag who has a class 'class_name'
    """
    return tag.find("span", class_=class_name)


class Document:
    """
    Represent a HTML document in response to a query from motmalagasy.org
    """

    def __init__(self, file_content):
        """
        Constructor

        Parameters
        ----------
        file_content: string
            content of the HTML file
        """

        soup = bs4.BeautifulSoup(file_content, 'html.parser')

        # self.soup is a <html> tag object
        self.soup = soup

        # 'rich' module for pretty printing
        self.console = Console()


    def get_entry_word(self) -> str:
        """
        Get the keywords entered by the user
        In french: Entrée
        """
        # find the 'entryWord' class
        entry_word_tag: bs4.Tag = get_class(self.soup, "entryWord")
        # the result of the above expression is always in the format:
        # <span class="entryWord">lako<u>zi</u>a<a class="entryWord" name="mg.n"> </a></span>
        # ... so we need to flatten it
        entry_word = ""
        for child in entry_word_tag.children:
            # append to result if 'child' is a NavigableString
            entry_word += child if type(child) == bs4.element.NavigableString else child.string
        return entry_word


    def get_result_pairs(self) -> list:
        """
        Get all the pair of result.
        e.g:
            Entrée: lakozia
            Partie du discours: nom
            Vocabulaire Economie: alimentation

        We need to get a table tag, which some particular attribute:
            - name="td"
            - width="20%"
            - align="right"

        Returns
        -------
        list
            Each row is a key-value pair:
                {
                    "label": "Explication en malgache",
                    "text": "Trano fanaovana nahandro"
                }
        """
        tables: list = self.soup.find_all(name="td", width="20%", align="right")
        new_entry = {}

        for table in tables[:-1]:
            # tables[:-1] because I removed the "Morphologie"
            # table[4:] because we do not want to print the first 4 <table>,
            # which is the navigation menu and some unknown BS!
            # TODO: this needs a hard edit cuz that guy was fkn lazy!

            # remove <span class="minute">
            minute = table.next_sibling.next_sibling.find("span", class_="minute")
            if minute != None:
                minute.extract()

            # take a look at the html file (result.html) to understand this section
            # put next_sibling 2 times because look at https://www.crummy.com/software/BeautifulSoup/bs4/doc/#next-sibling-and-previous-sibling
            new_entry[table.string] = "".join(table.next_sibling.next_sibling.stripped_strings)


        return new_entry

    def print_table(self):
        """
        Get the json representation of get_result_pairs()
        """
        return json.dumps(self.get_result_pairs())


def main():
    argv = sys.argv

    if len(argv) != 2:
        print("Incorrect number of arguments!")
        print("Usage: {} STRING".format(argv[0]))
        sys.exit(1)

    doc = Document(argv[1])
    print(doc.print_table())


if __name__ == '__main__':
    main()
