#!/usr/bin/env python

# This script takes a html string and
# print in JSON format to the stdout the result of the web parsing 

import os, sys, json
import typing

def print_module_error(module_name):
    print(f"{module_name} is required! Maybe you forget to enable a virtual environment!")

try:
    import bs4
except ModuleNotFoundError:
    print_module_error("bs4")
    sys.exit(2)


try:
    from rich.console import Console
except ModuleNotFoundError:
    print_module_error("rich")
    sys.exit(3)


def get_class(tag, class_name) -> bs4.Tag :
    """
    Search for a tag who has a class 'class_name'
    """
    return tag.find("span", class_=class_name)


class Document:
    """
    Represent a HTML document in response to a query from motmalagasy.org
    """

    def __init__(self, file_content):
        """
        Constructor

        Parameters
        ----------
        file_content: string
            content of the HTML file
        """

        soup = bs4.BeautifulSoup(file_content, 'html.parser')

        # self.soup is a <html> tag object
        self.soup = soup

        # 'rich' module for pretty printing
        self.console = Console()


    def get_entry_word(self) -> str:
        """
        Get the keywords entered by the user
        In french: Entrée
        """
        # find the 'entryWord' class
        entry_word_tag: bs4.Tag = get_class(self.soup, "entryWord")
        # the result of the above expression is always in the format:
        # <span class="entryWord">lako<u>zi</u>a<a class="entryWord" name="mg.n"> </a></span>
        # ... so we need to flatten it
        entry_word = ""
        for child in entry_word_tag.children:
            # append to result if 'child' is a NavigableString
            entry_word += child if type(child) == bs4.element.NavigableString else child.string
        return entry_word


    def get_result_pairs(self) -> list:
        """
        Get all the pair of result.
        e.g:
            Entrée: lakozia
            Partie du discours: nom
            Vocabulaire Economie: alimentation

        We need to get td tags, which some particular attribute:
            - width="20%"
            - align="right"

        Returns
        -------
        list
            Each row is a key-value pair:
                {
                    "label": "Explication en malgache",
                    "text": "Trano fanaovana nahandro"
                }
        """

        # get all <td> tag with some particular attributes
        # `tables` is a list of `bs4.Tag`
        tables: list = self.soup.find_all(name="td", width="20%", align="right")
        assert type(tables[0] == bs4.Tag)

        new_entry = {}

        for table in tables[:-1]:

            # remove <span class="minute">
            minute = table.next_sibling.next_sibling.find("span", class_="minute")
            if minute != None:
                minute.extract()

            # Flatten the <td> tag because it can contains multiple children tag
            # Take a look at the html file (result.html) to understand this section
            # `table.string` is the key
            # `next_sibling` property is applied 2 times because the first sibling is a whitespace
            # Look at https://www.crummy.com/software/BeautifulSoup/bs4/doc/#next-sibling-and-previous-sibling

            # if the key (`table.string`) is 'Morphologie', create a child dict because it contains sub key
            if table.string == 'Morphologie':
                # Get <span class='mgtr'>
                subkey = table.next_sibling.next_sibling.find_all("span", class_="mgtr")
                assert type(subkey) == bs4.Tag
                new_entry[table.string] = {}
                for s in subkey:
                    new_entry[table.string][s] = s.parent.next_sibling.stripped_strings
            else:
                new_entry[table.string] = "".join(table.next_sibling.next_sibling.stripped_strings)


        return new_entry

    def print_table(self):
        """
        Get the json representation of get_result_pairs()
        """
        return json.dumps(self.get_result_pairs())


def main():
    argv = sys.argv

    if len(argv) != 2:
        print("Incorrect number of arguments!")
        print("Usage: {} STRING".format(argv[0]))
        sys.exit(1)

    doc = Document(argv[1])
    print(doc.print_table())


if __name__ == '__main__':
    main()
