on:
  push:
    tags:
      - "*"
    # on test branch
    branches:
      - iss28

permissions:
    contents: write

jobs:
  release:
    name: release on linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --force --tags
          
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.20.0'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
